package com.lambdaschool.countries.models;

import javax.persistence.*;

@Entity
@Table(name = "countries")
public class Country {
//    countryid, name, population, landmasskm2, medianage
    //primary key for countries autogenerated at discretion of database
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    long countryid;

    //name of country
    String name;

    //population of country
    long population;

    //landmass in kilometers squared
    long landmasskm2;

    //median age of the population
    int medianage;

    //constructor so we can add more countries to the list
    public Country(
        String name,
        long population,
        long landmasskm2,
        int medianage)
    {
        this.name = name;
        this.population = population;
        this.landmasskm2 = landmasskm2;
        this.medianage = medianage;
    }

    // default constructor so Spring Data PJA doesn't yell at us
    public Country()
    {
    }

    //countryid
    public long getCountryid()
    {
        return countryid;
    }

    //name
    public String getName()
    {
        return name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    //population
    public long getPopulation()
    {
        return population;
    }

    public void setPopulation(long population)
    {
        this.population = population;
    }

    //land mass km^2
    public long getLandmasskm2()
    {
        return landmasskm2;
    }

    public void setLandmasskm2(long landmasskm2)
    {
        this.landmasskm2 = landmasskm2;
    }

    //median age
    public int getMedianage()
    {
        return medianage;
    }

    public void setMedianage(int medianage)
    {
        this.medianage = medianage;
    }

    //custom toString method let's us console log more easily
    @Override
    public String toString()
    {
        return "Country{" +
            "countryid=" + countryid +
            ", name='" + name + '\'' +
            ", population=" + population +
            ", landmasskm2=" + landmasskm2 +
            ", medianage=" + medianage +
            '}';
    }
}
